config/routes.rb
Rails.application.routes.draw do

 

  get 'pages/home'# before when it was not working i had, get 'home', to: 'pages#home' SMH -_-

  get 'pages/about'

  resources :articles #added this by ourselves to get all the routes from creating,deleting, showing etc

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user 
	validates :title, presence: true, length: { minimum: 10, maximum: 30}
	validates :description, presence: true, length: { minimum: 20, maximum: 70}
	validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base 
	has_many :articles #you put the connections in the model files 
	before_save {self.email = email.downcase} #makes it so that the email gets put downcase b4 hitting the DB
	validates :username, presence: true, uniqueness: {case_sensitive: false} , length: {minimum: 4, maximum: 20}
	VALID_EMAIL_REGEX = /\A[\w+\-]+@[a-z\d\-_]+\.[a-z]+\z/i
	validates :email, presence: true, uniqueness: {case_sensitive: true}, length: {minimum: 5, maximum: 20}, format: {with: VALID_EMAIL_REGEX}
end 

#oook so it appears that the hashes are used when you want to add attributes to a statement , get it bro?

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController  < ApplicationController
	before_action :set_article, only: [:edit, :update, :show, :destroy]

	def index
		@articles = Article.all
	end 

	def new 
		@article = Article.new 
	end 


	def edit
	end

	def create 
		debugger 
		@article = Article.new(article_params)
		@article.user = User.third
		if @article.save 
		flash[:success] = "Congrats, your article was succefully saved"
		redirect_to article_path(@article)
		else 
		flash[:danger] = "The article was not able to be saved"
		render 'new' 
	end
end

def update
	
	if @article.update(article_params)
		flash[:success] = "Congrats, your article was successfully updated"
		redirect_to article_path(@article) 
	else 
		flash[:danger] = "Error, your article, was not updates for the following errors.."
		render 'edit'
	end 
end

	def show
        #the article is passed into the instance variable that find the article by finding the unique id 
	end 

	def destroy 
		@article.destroy 
		flash[:danger] = "Article was successfully destroyed"
		redirect_to articles_path
	end

	private

	def set_article
		@article = Article.find(params[:id])
	end

	def article_params
		params.require(:article).permit(:title, :description)
	end 
	
	  
end 

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%=  render 'shared/errors', obj: @article  %><!-- this is how you swich what an object is called LOL -->
<div class="row">
	<div class="col-xs-12">
<%=form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %><!--space inbetween form_for & @article actually caused an issue-->
<div class="form-group">
	<div class="control-label col-sm-2">
		<%= f.label :title %>
</div>
<div class="col-sm-8">
	<%= f.text_field :title, class: "form-control", placeholder: "Title of Article", autofocus: true %><!--notice autofocus -->
</div>
<br>
<br>
<br><!--added the br tags to fix that they were too close -->
<div class="form-group">
	<div class="control-label col-sm-2">
	<%= f.label :description %>
</div>

<div class="col-sm-8">
	<%= f.text_area :description,rows: 10, class:"form-control", placeholder: "Body of Article"%>
</div>
</div>
    <div class="form-group">
    	<div class="col-sm-offset-2 col-sm-10">
    <%= f.submit class: "btn btn-primary btn-lg" %>
</div>
</div>
<% end %>
<div class="col-xs-4 col-xs-offset-4">
[ <%= link_to "Cancel request and go back to Articles Listing", articles_path %> ]
</div>
</div>
</div>





<!--When the autofocus attribute is present, the INPUT, TEXTAREA, or BUTTON element is automatically selected upon page load. I experimented with display elements (H1 tag) and a tabIndex of 0, but autofocus did not work for them.

This attribute is especially useful on pages whose main purpose is collecting information, like Google's homepage (search is the use 99% of the time) or even an online guided installer (like WordPress' installer). And best of all  no JavaScript needed!-->


<!-- col-sm-offset-'whatever number' reduces the primary set col by what ever you specifiy-->

app/views/articles/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" id="logo" href="#">Udemy</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="hover"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/articles/edit.html.erb
<h2 align="center">Edit Article</h2>



<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Listing all Articles</h1>


<%= @articles.each do |article| %>
<div class="row">
	<div class="col-xs-8 col-xs-offset-2">
		<div class="well well-lg">
			<div class="article-title">
				<%= link_to article.title, article_path(article) %>
			</div>

			<div class="article-body">
				<%= truncate(article.description, 
				   length: 100) %>

				   <div class = "article-meta-details">
				       <small>Created by: <%= article.user.username if article.user%>, 
					     <%= time_ago_in_words(article.created_at) %> ago, 
					     last_updated: <%= time_ago_in_words(article.updated_at) %> ago </small> 
					 </div>
				</div>

				<div class="article-actions">
 <%= link_to "Edit Article", edit_article_path(article),       class: "btn btn-xs btn-primary" %>

 <%=  link_to "Delete this Article",article_path(article),      method: :delete, data: {confirm: "Are you sure?"},
              class: "btn btn-xs btn-danger" %>

       	</div>
       </div>
   </div>
</div>
<% end %>

	<!-- edited this b4 leaving lib 
	  changed @article  to artile to match code block 
	  pasted buttons from show page 
	  deleted the last one bcu you didnt need it -->

app/views/articles/new.html.erb
<h1 align="center"> Create an Article</h1><!--even if you render a doc the print on the page still shows-->
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center"> <%= @article.title%></h2>
<div class="well col-xs-8 col-xs-offset-2"><!--look at the well-->
	<h4 class="center description"><strong>Description</strong></h4><!--look at the 'class=center'-->
	<hr>
	<%= simple_format(@article.description) %>
	<div class="article-actions">
 <%= link_to "Edit Article", edit_article_path(@article),       class: "btn btn-xs btn-primary" %>

 <%=  link_to "Delete this Article",article_path(@article),      method: :delete, data: {confirm: "Are you sure?"},
              class: "btn btn-xs btn-danger" %>

 <%= link_to "Go back to all Articles", articles_path, 
       class: "btn btn-xs btn-success" %>

       	</div>
       </div>

app/views/layouts/_footer.html.erb
<div class="container">
	<footer class="footer"><!--notice the footer tag-->
		<small>
			Copyright &copy; <a href="https://www.udemy.com/the-complete-ruby-on-rails-developer-course/learn/v4/t/lecture/3851042">My Udemy Course</a> by <a href="https://www.udemy.com/the-complete-ruby-on-rails-developer-course/learn/v4/t/lecture/3851042">Same Course</a>
		</small>
		<nav><!--notice the nav tag-->
			<ul>
			</li><%= link_to "About", pages_about_path %></li>
		</ul>
	</nav>
</footer>
</div>

app/views/layouts/_messages.html.erb
    <div class="row">
    	<div class="col-xs-10 col-xs-offset-1">
    		<% flash.each do |name,msg| %>
    		<div class='alert alert-<%="#{name}" %> '>
    			<a href="#" class="close" data-dismiss="alert">&#215;</a>
    			<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    		</div>
    		<% end %>
    	</div>
    </div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default" id="the-whole-navbar">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#" id="the-mac-title">MAC</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%=link_to "Articles", articles_path %></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "New Article", new_article_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      
      
      <ul class="nav navbar-nav navbar-right">

          <button type="button" class="btn btn-danger btn-md" id="contact-link" data-toggle="modal" data-target="#myModal">Notary!</button>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Contact Info</h4>
      </div>
      <div class="modal-body">
        <ul>
          <li>email</li>
          <li>phone</li>
          <li>fax</li>
        </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Udemy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/navigation' %>
	<%= render 'layouts/messages' %>
	<div class="container">
<%= yield %>
</div>
<%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %> 
</body>
</html>

app/views/pages/about.html.erb
<html>
<header>
<div class="container">
	<div class="jumbotron">
		<h1 id="the-title">>MAC Settelment Services</h1>
	</div>
</div>

app/views/pages/home.html.erb
<html>
<div id="the-whole-body">
<header>
   <div class="center jumbotron">
		<h1 id="the-title">MAC Settlement Services</h1>
		<%= link_to "Sign up Now", "#", class: "btn btn-danger btn-lg"%>
	</div>



<body>

	</body>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
	<div class="col-xs-8 col-xs-offset-2">
		<div class="panel panel-danger">
			<div class="panel-heading">
				<h2 class="panel-title">
					<%= pluralize(obj.errors.count, "error") %>
					prohibited this article from being saved: 
				</h2>
				<div class="panel-body">
					<ul>
						<% obj.errors.full_messages.each do |msg| %> 
						<li><%= msg %></li>
						<% end %>
					</ul>
				</div>
			</div>
		</div>
		<% end %>